# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: photon/imessage/v1/address_service.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'photon/imessage/v1/address_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from photon.imessage.v1 import address_types_pb2 as photon_dot_imessage_dot_v1_dot_address__types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(photon/imessage/v1/address_service.proto\x12\x12photon.imessage.v1\x1a\x1cgoogle/api/annotations.proto\x1a&photon/imessage/v1/address_types.proto\"(\n\x15GetAddressInfoRequest\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\"S\n\x16GetAddressInfoResponse\x12\x39\n\x04info\x18\x01 \x01(\x0b\x32+.photon.imessage.v1.MultiServiceAddressInfo\"(\n\x15GetFocusStatusRequest\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\"6\n\x16GetFocusStatusResponse\x12\x1c\n\x14is_silenced_by_focus\x18\x01 \x01(\x08\"1\n\x1eGetIMessageAvailabilityRequest\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\"7\n\x1fGetIMessageAvailabilityResponse\x12\x14\n\x0cis_available\x18\x01 \x01(\x08\x32\xd4\x03\n\x0e\x41\x64\x64ressService\x12\x83\x01\n\x0eGetAddressInfo\x12).photon.imessage.v1.GetAddressInfoRequest\x1a*.photon.imessage.v1.GetAddressInfoResponse\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/v1/addresses:info\x12\x8a\x01\n\x0eGetFocusStatus\x12).photon.imessage.v1.GetFocusStatusRequest\x1a*.photon.imessage.v1.GetFocusStatusResponse\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/v1/addresses:focusStatus\x12\xae\x01\n\x17GetIMessageAvailability\x12\x32.photon.imessage.v1.GetIMessageAvailabilityRequest\x1a\x33.photon.imessage.v1.GetIMessageAvailabilityResponse\"*\x82\xd3\xe4\x93\x02$\x12\"/v1/addresses:imessageAvailabilityB\t\xba\x02\x06PIMsg_b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'photon.imessage.v1.address_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\272\002\006PIMsg_'
  _globals['_ADDRESSSERVICE'].methods_by_name['GetAddressInfo']._loaded_options = None
  _globals['_ADDRESSSERVICE'].methods_by_name['GetAddressInfo']._serialized_options = b'\202\323\344\223\002\024\022\022/v1/addresses:info'
  _globals['_ADDRESSSERVICE'].methods_by_name['GetFocusStatus']._loaded_options = None
  _globals['_ADDRESSSERVICE'].methods_by_name['GetFocusStatus']._serialized_options = b'\202\323\344\223\002\033\022\031/v1/addresses:focusStatus'
  _globals['_ADDRESSSERVICE'].methods_by_name['GetIMessageAvailability']._loaded_options = None
  _globals['_ADDRESSSERVICE'].methods_by_name['GetIMessageAvailability']._serialized_options = b'\202\323\344\223\002$\022\"/v1/addresses:imessageAvailability'
  _globals['_GETADDRESSINFOREQUEST']._serialized_start=134
  _globals['_GETADDRESSINFOREQUEST']._serialized_end=174
  _globals['_GETADDRESSINFORESPONSE']._serialized_start=176
  _globals['_GETADDRESSINFORESPONSE']._serialized_end=259
  _globals['_GETFOCUSSTATUSREQUEST']._serialized_start=261
  _globals['_GETFOCUSSTATUSREQUEST']._serialized_end=301
  _globals['_GETFOCUSSTATUSRESPONSE']._serialized_start=303
  _globals['_GETFOCUSSTATUSRESPONSE']._serialized_end=357
  _globals['_GETIMESSAGEAVAILABILITYREQUEST']._serialized_start=359
  _globals['_GETIMESSAGEAVAILABILITYREQUEST']._serialized_end=408
  _globals['_GETIMESSAGEAVAILABILITYRESPONSE']._serialized_start=410
  _globals['_GETIMESSAGEAVAILABILITYRESPONSE']._serialized_end=465
  _globals['_ADDRESSSERVICE']._serialized_start=468
  _globals['_ADDRESSSERVICE']._serialized_end=936
# @@protoc_insertion_point(module_scope)
